version: '3.1'
services:
  nps:
    image: ffdfgdfg/nps
    container_name: nps
    restart: always
    network_mode: host
    volumes:
      - /opt/docker/nps:/conf
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    restart: unless-stopped
    network_mode: host
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /opt/docker/nginx/data:/data
      - /opt/docker/nginx/letsencrypt:/etc/letsencrypt
    deploy:
      resources:
        limits:
          memory: 256M


networks:
  service:
    external: true