version: "2.2"
services:
  jobmanager:
    image: flink:1.14.4-scala_2.11-java8
    ports:
      - "8081:8081"
    command: jobmanager
    container_name: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        

  taskmanager:
    image: flink:1.14.4-scala_2.11-java8
    depends_on:
      - jobmanager
    command: taskmanager
    container_name: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2